version: '3.8'
services:
    backend:
        build: ./backend
        ports:
            - '5001:5001'
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - SERVER_PORT=${SERVER_PORT}
    frontend:
        build: ./frontend
        ports:
            - '3000:3000'
        environment:
            - VITE_BACKEND_URL=http://host.docker.internal:5001
            - VITE_HOST=0.0.0.0
            - VITE_FRONTEND_PORT=3000
        depends_on:
            - backend
